name = "blog-download-worker"
main = "src/index.ts"
compatibility_date = "2026-08-09"

[[r2_buckets]]
binding = "BLOG_DOWNLOADS"
bucket_name = "blog-downloads"

[[d1_databases]]
binding = "DB"
database_name = "blog-downloads-db"
database_id = "bf8f414a-717a-4fac-aec9-8930dddcae19"  # fill after `wrangler d1 create`
