name = "blog-download-worker"
main = "src/index.ts"
compatibility_date = "2026-08-09"

[[r2_buckets]]
binding = "BLOG_DOWNLOADS"
bucket_name = "blog-downloads"

[[d1_databases]]
binding = "DB"
database_name = "blog-downloads-db"
database_id = "76f32689-ce8f-4ba5-9f78-404071a2e20b"  # fill after `wrangler d1 create`
